name: openvino-benchmark-app # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2024.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: OpenVINO toolkit libraries # 79 char long summary
description: |
  OpenVINO toolkit full description

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  openvino-benchmark-app:
    command: usr/local/samples_bin/benchmark_app
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/openvino-libs:$SNAP/openvino-extra-libs

plugs:

  openvino-libs:
    interface: content
    content: openvino-libs
    target: $SNAP/openvino-libs
    default-provider: openvino-libs-test

  openvino-3rdparty-libs:
    interface: content
    content: openvino-extra-libs
    target: $SNAP/openvino-extra-libs
    default-provider: openvino-libs-test

parts:
  openvino-build:
    plugin: cmake
    source-type: git
    source: https://github.com/mryzhov/openvino.git
    source-branch: master
    override-build: |
      cmake $SNAPCRAFT_PART_SRC/samples/cpp
      cmake --build .
      cmake --install . --component samples_bin --prefix $SNAPCRAFT_PART_INSTALL/usr/local
    build-environment:
      - CMAKE_BUILD_PARALLEL_LEVEL: ${SNAPCRAFT_PARALLEL_BUILD_COUNT}
      - CMAKE_BUILD_TYPE: Release
      - CMAKE_INSTALL_PREFIX: $SNAPCRAFT_PART_INSTALL/usr/local
      - OpenVINO_DIR: /snap/openvino-libs-test/current/usr/local/runtime/cmake
      - LD_LIBRARY_PATH: $LD_LIBRARY_PATH:/snap/openvino-libs-test/current/usr/local/runtime/3rdparty/tbb/lib
    build-packages:
      - build-essential
      - ninja-build
      - pkg-config
      - gzip
    build-snaps:
      - openvino-libs-test
    prime:
      - usr/local/samples_bin/benchmark_app