name: openvino-libs-test # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2024.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: OpenVINO toolkit libraries # 79 char long summary
description: |
  OpenVINO toolkit full description

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

slots:

  openvino-libs:
    interface: content
    content: openvino-libs
    read:
      - $SNAP/usr/local/lib

  openvino-3rdparty-libs:
    interface: content
    content: openvino-extra-libs
    read:
      - $SNAP/usr/local/runtime/3rdparty/tbb/lib

parts:
  openvino-build:
    plugin: cmake
    source-type: git
    source: https://github.com/mryzhov/openvino.git
    source-branch: snap
    cmake-generator: Ninja
    cmake-parameters:
      - -DCPACK_GENERATOR=SNAP
      - -DENABLE_SAMPLES:BOOL=OFF
      - -DENABLE_TESTS:BOOL=OFF
      - -DENABLE_JS:BOOL=OFF
      - -DENABLE_INTEL_GPU:BOOL=OFF
      - -DENABLE_PYTHON:BOOL=OFF
      - -DENABLE_OV_ONNX_FRONTEND=OFF
      - -DENABLE_OV_PADDLE_FRONTEND=OFF
      - -DENABLE_OV_PYTORCH_FRONTEND=OFF
      - -DENABLE_OV_TF_FRONTEND=OFF
      - -DENABLE_OV_TF_LITE_FRONTEND=OFF
    build-environment:
      - CMAKE_BUILD_PARALLEL_LEVEL: ${SNAPCRAFT_PARALLEL_BUILD_COUNT}
      - CMAKE_BUILD_TYPE: Release
    build-packages:
      - build-essential
      - ninja-build
      - pkg-config
      - gzip
